title: My Personal Website
author: My Duc Tran 
description: >- 
        My place to share my thought and my projects & some delicious recipes. 
baseurl: "" 
url: "https://mytran2111.github.io/" 
github_username: mytran2111


markdown: kramdown
theme: jekyll-theme-architect
