title: My Personal Website
author: My Duc Tran 
description: >- 
        My place to share my thought and my projects & some delicious recipes. 
baseurl: "" 
url: "https://mytran2111.github.io/" 
email: 'my.d.tran@mail.mcgill.ca'
linkedin: 'https://www.linkedin.com/in/my-duc-tran-2341a8191/'
github_username: mytran2111


markdown: kramdown
theme: jekyll-theme-architect
