title: My Personal Website
author: My Duc Tran 
description: >- 
        BSc. Statistics and Computer Science @ McGill  
baseurl: "" 
url: "https://mytran2111.github.io/" 
email: 'my.d.tran@mail.mcgill.ca'
linkedin: 'https://www.linkedin.com/in/my-duc-tran-2341a8191/'
github_username: mytran2111


markdown: kramdown
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-remote-theme
